version: '3.8'

services:
  # Databases
  auth-db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  employee-db:
    image: postgres:13
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  attendance-db:
    image: postgres:13
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  # Services
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - auth-db

  employee-service:
    build: ./employee-service
    ports:
      - "3002:3002"
    depends_on:
      - employee-db

  attendance-service:
    build: ./attendance-service
    ports:
      - "3003:3003"
    depends_on:
      - attendance-db

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - employee-service
      - attendance-service
